### ISSUE TITLE
Crysis Remastered issue with wine

### ISSUE THREAD

**Issue by liberodark** [Riesi/CChromaEditor#1]
Hi,

You have possibility to make x64 workaround ?
For : CChromaEditorLibrary64.dll

```
ERROR: Could Not Get Primary Adapter Handle
Validated all DLL methods [success]
ChromaSDKPlugin failed to load!
00b0:err:seh:call_stack_handlers invalid frame 120000 (0000000000122000-0000000000220000)
00b0:err:seh:NtRaiseException Exception frame is not in stack limits => unable to dispatch exception.
```

https://github.com/ValveSoftware/Proton/issues/896#issuecomment-714378706

Best Regards.

**Comment by Riesi** [comment]
Not sure, if it will change anything, but here you go.
[CChromaEditorLibrary64.zip](https://github.com/Riesi/CChromaEditor/files/5434605/CChromaEditorLibrary64.zip)
Normally games should be ok with it failing to load, because otherwise it would certainly break on non Razer hardware on Windows too.
